// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC6_SQL_ViewModel.Models
{
    public partial class DepartmentTable2
    {
        //一對多
        public DepartmentTable2()
        {
            UserTable2 = new HashSet<UserTable2>();
        }
        [Key]
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentY { get; set; }

        //導覽屬性
        public virtual ICollection<UserTable2> UserTable2 { get; set; }
    }
}