// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using MVC6_SQL_ViewModel.Models;

namespace MVC6_SQL_ViewModel.Models
{
    public partial class MVC_UserDB2Context : DbContext
    {
        public MVC_UserDB2Context()
        {
        }

        public MVC_UserDB2Context(DbContextOptions<MVC_UserDB2Context> options)
            : base(options)
        {
        }

        public virtual DbSet<DepartmentTable2> DepartmentTable2 { get; set; }
        public virtual DbSet<UserTable2> UserTable2 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DepartmentTable2>(entity =>
            {
                entity.HasKey(e => e.DepartmentId);

                entity.Property(e => e.DepartmentName).HasMaxLength(50);

                entity.Property(e => e.DepartmentY).HasMaxLength(50);
            });

            modelBuilder.Entity<UserTable2>(entity =>
            {
                entity.HasKey(e => e.UserId);

                entity.Property(e => e.UserMobilePhone).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);

                entity.Property(e => e.UserSex)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.DepartmentTable2)
                    .WithMany(p => p.UserTable2)
                    .HasForeignKey(d => d.DepartmentId)
                    .HasConstraintName("FK_UserTable2_DepartmentTable2");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public DbSet<MVC6_SQL_ViewModel.Models.UserTable2ViewModel>? UserTable2ViewModel { get; set; }
    }
}